config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :clubs do
    resources :meetings, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  end

  resources :meetings, only: [:index, :show, :new, :create, :edit, :update]

  root "sessions#new"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  post "/join", to: "users#join"
  get "/signout", to: "sessions#destroy"
  post "/leave", to: "users#leave"
  get '/auth/facebook/callback' => 'sessions#create'
  post "/admin", to: "clubs#make_admin", :as => 'admin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :user_clubs, dependent: :destroy
  has_many :users, :through => :user_clubs
  has_many :meetings

  scope :open_clubs, -> { where(has_max: false) }

  validates :name, presence: true, :length => {:within => 5..30}, on: :create

  def is_admin?(user)
    self.admin == user.id
  end

  def reached_max
    if self.users.count == 5
      self.has_max = true
    end
  end

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :club
  has_many :users
end

app/models/session.rb
class Session < ActiveRecord::Base
  before_save :downcase_fields

  def downcase_fields
    self.email.downcase!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :user_clubs
  has_many :clubs, :through => :user_clubs
  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, on: :create
  validates :password, presence: true, :length => {:within => 6..40}, on: :create
  validates :password, presence: true, :length => {:within => 6..40}, on: :update

  before_save :downcase_fields

  def downcase_fields
    self.email.downcase!
  end

end

app/models/user_club.rb
class UserClub < ActiveRecord::Base
  belongs_to :user
  belongs_to :club
end

app/models/users_clubs.rb
class UsersClubs < ApplicationRecord
  belongs_to :user
  belongs_to :club
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :require_logged_in, except: [:new, :create]
  before_action :set_cache_headers

  def logged_in?
    !!current_user
  end

  private
    def require_logged_in
      redirect_to root_path unless logged_in?
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def set_cache_headers
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    end

    helper_method :current_user
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destory]

  def index
    @clubs = Club.all
  end

  def new
    @club = Club.new
  end

  def show
    @club = Club.find(params[:id])
  end

  def create
    @club = Club.new(club_params)
    @club.admin = current_user.id
    if @club.save # need to get rid of this, since instance `@club.users << current_user`
      @club.users << current_user
      @club.save
      redirect_to @club, notice: "Club was successfully created."
    else
      render :new
    end
  end

  def make_admin
    @club = Club.find(params[:club_id])
    @user = User.find(params[:user_id])
    @club.admin = @user.id
    @club.save
    redirect_to club_path(@club)
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    redirect_to user_path(@club.admin)
  end

  private
    def set_club
      @club = Club.find(params[:id])
    end

    def club_params
      params.require(:club).permit(
        :name,
        :club_category,
        :description
      )
    end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destory]
  def index
    if params[:club_id]
      @meetings = Club.find(params[:club_id]).meetings
    else
      @meetings = Meetings.all
    end
  end

  def show
    @meeting = Meeting.find(params[:id])
  end

  def new
    @club = Club.find(params[:club_id])
    @meeting = @club.meetings.build
  end

  def create
    @club = Club.find(params[:club_id])
    @club.meetings.build(meeting_params)
    if @club.save
      redirect_to club_path(@club), notice: "Meeting was succesfully created."
    else
      render :new
    end
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update(meeting_params)
      redirect_to club_path(@meeting.club_id), notice: "Update Successful."
    else
      redirect_to club_path(@meeting.club_id), notice: "Failed to Update."
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to club_path(@meeting.club_id)
  end

  private
    def meeting_params
      params.require(:meeting).permit(
        :name,
        :description,
        :count,
        :meeting_datetime,
      )
    end

    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
require 'pry'

class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) unless !current_user
    @user = User.new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      oauth_email = request.env["omniauth.auth"]["info"]["email"]
      oauth_name = request.env["omniauth.auth"]["info"]["name"]
      oauth_image = request.env["omniauth.auth"]["info"]["image"]
      if @user = User.find_by(:email => oauth_email)
        session[:user_id] = @user.id

        redirect_to user_path(@user)
      else
        first_name = oauth_name.split.first
        last_name = oauth_name.split.last
        @user = User.new(:first_name => first_name, :last_name => last_name, :email => oauth_email, :password_digest => SecureRandom.hex, :image => oauth_image)
        @user.password = SecureRandom.hex

        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          raise @user.errors.full_messages.inspect
        end
      end
    else
      # Normal Login with email/password
      @user = User.find_by(email: params[:user][:email])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        redirect_to signin_path
      end
    end
  end

  def destroy
    session.delete :user_id

    redirect_to root_url
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @clubs = Club.all
  end

  def show
    @clubs = Club.last(2)
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "Update Successful."
    else
      redirect_to user_path(@user), notice: "Failed to Update."
    end
  end

  def join
    @club = Club.find(params[:club_id])
    @club.users << current_user
    @club.user_clubs.last.favorite_club = true
    @club.reached_max
    if @club.save
      redirect_to club_path(@club), notice: "Congratulations! You've joined this club."
    else
      redirect_to @club, notice: "I'm sorry, you were not able to join this club."
    end
  end

  def leave
    @club = Club.find(params[:club_id])
    current_user.clubs.destroy(@club)
    redirect_to @club, notice: "You have successfully left this club!"
  end

  private

    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :admin
      )
    end

    def set_user
      @user = User.find(params[:id])
    end



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/clubs/index.html.erb
<div class="center">
  <h1>Clubs</h1>
</div>


<% @clubs.open_clubs.each do |club| %>
  <% if !club.users.include? current_user %>
    <%= link_to "#{club.name}", club_path(club) %><br>
  <% end %>
<% end %>

<div class="row">
  <% @clubs.open_clubs.each do |club| %>
      <form class="col-sm-3 mb-3" method="POST" action="/clubs/:id">
          <div class="card text-dark mb-3" style="max-width: 18rem;">
          <input type="hidden" name="club" value=<%=club["id"]%> placeholder="Club Name"></input>
              <div class="card-header"><%= club["name"] %></div>
              <div class="card-body">
                  <h5 class="card-title"><%= club["description"] %></h5>
              </div>
              <button class="btn btn-light" style="width: 100%;" type="submit">Join</button>
          </div>
      </form>
  <% end %>
</div>

app/views/clubs/new.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors</h2>
      <ul>
        <% @club.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Club Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :club_category %><br>
    <%= f.text_field :club_category %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "55x8" %>
  </div>
  <div class="actions">
  	<%= f.submit :Submit, class: 'btn btn-success' %>
  	<%= link_to "cancel", root_path, :class=>"btn btn-xs btn-danger" %>
  </div>

<% end %>

app/views/clubs/show.html.erb
<div class="center">
  <h1><%= @club.name + " - " + "Members: #{@club.users.count}" %></h1>
  <p>"<%= @club.description %>"</p>
</div>

<div class="center">
  <% if @club.users.include? current_user %>
    <%= button_to 'Leave Club', { :controller => "users", :action => "leave", :club_id => @club.id, :user_id=> session[:user_id] }, :method=>:post, data: { confirm: "Are you sure you want to leave this club?" }, class: 'btn btn-danger' %><br>
    <% if @club.is_admin?(current_user) %>
      <%= button_to 'Delete Club', { :controller => "clubs", :action => "destroy", :club_id => @club.id, :user_id=> session[:user_id] }, :method=>:delete, data: { confirm: "Are you sure you want to delete this club?" }, class: 'btn btn-danger' %>
    <% end %>
  <% else %>
    <%= button_to 'Join', { :controller => "users", :action => "join", :club_id => @club.id, :user_id=> session[:user_id] }, :method=>:post, class: "btn btn-primary" %><br>
  <% end %>
  <p id="notice"><%= notice %></p>
</div>

<h2><u>Club Members</u></h2>
<% @club.users.each do |user| %>
  <ul>
    <li>
      <%= link_to "#{ user.first_name } #{ user.last_name }", user_path(user) %>
      <% if @club.is_admin?(current_user) && (@club.admin != user.id) %>
        <%= button_to 'Make Admin', {:controller => "clubs", :action => "make_admin", :club_id => @club.id, :user_id=> user.id}, :method=>:post, class: "btn-xs btn-primary" %>
      <% end %>
      <% if user.id == @club.admin %>
        (Club Admin)
      <% end %>
    </li>
  </ul>
<% end %>
<hr>
<div class="center">
  <% if @club.is_admin?(current_user) %>
    <%= button_to 'New Meeting', { :controller => "meetings", :action => "new", :club_id => @club.id }, :method=>:get, class: 'btn btn-success' %><br>
  <% end %>
</div>

<% if @club.meetings %>
  <div class="center">

    <h3><u>Meetings</u></h3>
  </div>

  <%= render :collection => @club.meetings, :partial => "meetings/meeting_list", :as => :meeting %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
          <% if current_user %>
            <% if current_page?(user_path(current_user)) %>
              <a class="navbar-brand" href="<%= edit_user_path %>"/>Edit</a>
            <% end %>
            <a class="navbar-brand" href="<%= signout_path %>"/>Logout</a>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for [@club, @meeting] do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors</h2>
      <ul>
        <% @meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :meeting_datetime, "Time of Meeting" %><br>
    <%= f.datetime_select :meeting_datetime, :discard_year => true %>
  </div>
  <div class="actions">
    <%= f.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/meetings/_meeting_list.html.erb
<div class="container">
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-body">
        <section class="post-heading">
          <h4><u><%= meeting.name %></u> - <%= meeting.meeting_datetime %></h4>
          <div class="row">
            <div class="col-md-11">
              <section class="post-body">
                <p><%= meeting.description %></p>
              </section>
              <% if @club.is_admin?(current_user) %>
                <%= form_tag(club_meeting_path(@club, meeting), :method => :delete) do %>
                  <button type="submit" class='btn btn-xs btn-danger' name="button">Delete</button>
                 <% end %>
                <%= link_to "Edit", edit_club_meeting_path(@club, meeting) %>
              <% end %>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/meetings/edit.html.erb
<%= render 'form' %><br>

app/views/meetings/new.html.erb
<%= form_for [@club, @meeting] do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors</h2>
      <ul>
        <% @meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :meeting_datetime, "Time of Meeting" %><br>
    <%= f.datetime_select :meeting_datetime, :discard_year => true %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <% if current_user %>
      <%= f.password_field :password, placeholder: "Current Password" %>
    <% else %>
      <%= f.password_field :password, placeholder: "New Password" %>
    <% end %>
  </div>
  <div class="actions">
    <br><%= f.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %><br>
<%= link_to "Sign in", root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-2">
    <% if @user.image %>
      <img src="<%= @user.image %>", class="user_pic">
    <% end %>
    <% if @user != current_user %>
      <h1><%= @user.first_name + " " + @user.last_name %></h1>
    <% end %>
  </div>
  <div class="col-md-6">
    <% if @user == current_user %>
      <h1>Welcome <%= @user.first_name + " " + @user.last_name %>!</h1>
    <% end %>
    <div class="mt-2">
      <% if @user == current_user %>
        <%= button_to 'Create Club', new_club_path, method: :get, class: 'btn btn-success' %><br>
        <%= link_to "Join New Club", clubs_path %><br>
      <% end %>
    </div>
  </div>
</div>

  <hr>

<div class="row">
  <div class="col-md-6">
    <h3><u><%= @user.first_name + "'s " %>Clubs</u></h3>
    <% @user.clubs.each do |club| %>
      <%= link_to club.name, club_path(club) %><br>
    <% end %>
  </div>
  <div class="col-md-6">
    <div class="list-group">
      <a href="<%= clubs_path %>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
              <p class="mb-1"><b>Recent Clubs Created</b></p>
          </div>
      </a>
      <% @clubs.each do |club| %>
        <a href="/clubs/<%= club.id %>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= club.name %></h5>
          </div>
          <p class="mb-1">Members: <%= club.users.count %> | Club Category: <%= club.club_category %></p>
          <small>Description: <%= club.description %></small>
        </a>
      <% end %>
    </div>
  </div>
</div>